### ISSUE TITLE
Image build fails

### ISSUE THREAD

**Issue by martin-helmich** [mittwald/harbor-operator#6]
Seems like quay.io is configured to build the harbor-operator images on its own (see https://quay.io/repository/mittwald/harbor-operator/build/f6eea9b7-6799-4be0-8061-33fbdfbcb512) -- which doesn't work, since the binary (that is supposed to be built by the operator SDK) isn't there when quay.io builds the image.

**Comment by elenz97** [comment]
This was a manual test i started to get the build status badge showing a successful build.
Though i don't think we even need builds done by quay.io, as the github workflow covers these already: https://github.com/mittwald/harbor-operator/blob/master/.github/workflows/workflow.yml#L72
Recent builds for `master` and `v0.1.1` were successful in the github workflow, yet quay.io only refers to them as tags (which is fine). Currently, i see no way of triggering an `operator-sdk build` on quay.io's side.

**Comment by elenz97** [comment]
Suggestion:
Replace the "quay.io container build failed" badge with a badge from the github workflow, e.g. ![Go](https://github.com/mittwald/harbor-operator/workflows/Go/badge.svg?branch=master)
